config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :notes
  resources :folders

  # Defines the root path route ("/")
  root "notes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/folder.rb
class Folder < ApplicationRecord
  has_many :notes, dependent: :destroy
  belongs_to :user

  COLORS = %w[dark blue azure indigo purple pink red orange yellow lime]
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  belongs_to :folder

  acts_as_taggable_on :tags

  has_rich_text :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notes, dependent: :destroy
  has_many :folders, dependent: :destroy

  after_create do
    self.folders.create(name: "Все записи", default: true)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_folder, only: %i[ show edit update destroy ]

  # GET /folders or /folders.json
  def index
    @folders = current_user.folders
  end

  # GET /folders/1 or /folders/1.json
  def show
  end

  # GET /folders/new
  def new
    @folder = current_user.folders.new
  end

  # GET /folders/1/edit
  def edit
  end

  # POST /folders or /folders.json
  def create
    @folder = current_user.folders.new(folder_params)

    respond_to do |format|
      if @folder.save
        format.html { redirect_to folder_url(@folder), notice: "Папка успешно создана" }
        format.json { render :show, status: :created, location: @folder }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /folders/1 or /folders/1.json
  def update
    respond_to do |format|
      if @folder.update(folder_params)
        format.html { redirect_to folder_url(@folder), notice: "Папка обновлена" }
        format.json { render :show, status: :ok, location: @folder }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /folders/1 or /folders/1.json
  def destroy
    @folder.destroy

    respond_to do |format|
      format.html { redirect_to folders_url, notice: "Папка была удалена" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_folder
      @folder = current_user.folders.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def folder_params
      params.require(:folder).permit(:name, :color)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes
  def index
    @notes = current_user.notes

    if params[:tagged].present?
      @notes = @notes.tagged_with(params[:tagged])
    end
  end

  # GET /notes/:id
  def show
  end

  # GET /notes/new
  def new
    @note = current_user.notes.new
  end

  # GET /notes/:id/edit
  def edit
  end

  # POST /notes
  def create
    @note = current_user.notes.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(@note), notice: "Запись успешно создана" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/:id
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: "Запись обновлена" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/:id
  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Запись была удалена" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = current_user.notes.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:title, :content, :tag_list, :folder_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% end %>
  </figcaption>
</figure>

app/views/folders/_color_buttons.html.erb
<div class="row g-2">
  <% Folder::COLORS.each do |color| %>
    <div class="col-auto">
      <label class="form-colorinput">
        <%= form.radio_button :color, color, class: "form-colorinput-input" %>
        <%= content_tag :span, "", class: "form-colorinput-color bg-#{color}" %>
      </label>
    </div>
  <% end %>
</div>

app/views/folders/_form.html.erb
<%= form_with model: folder, html: { class: "card mt-4" } do |form| %>
  <%= content_tag :div, nil, class: "card-status-top bg-#{folder.color}" %>
  <div class="card-body">
    <% if folder.errors.any? %>
      <div style="color: red">
        <ul>
          <% folder.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :name, "Название папки", class: "form-label" %>
      <%= form.text_field :name, placeholder: "Введите название", class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :color, "Выберите цвет", class: "form-label" %>
      <%= render "folders/color_buttons", form: form %>
    </div>
  </div>


  <div class="card-footer text-end">
    <div class="d-flex justify-content-between">
      <%= link_to "Назад", folders_path, class: "btn btn-link" %>
      <%= form.submit "Применить", class: "btn btn-primary ms-auto" %>
    </div>
  </div>
<% end %>

app/views/folders/edit.html.erb
<h1>Изменение папки</h1>

<div class="col-8 m-auto">
  <%= render "form", folder: @folder %>
</div>

app/views/folders/index.html.erb
<div class="d-flex">
  <h1>Мои папки</h1>
</div>

<div class="row row-cards mt-4" id="folders">
  <% @folders.each do |folder| %>
    <div class="col-md-6 col-xl-3">
      <div class="card card-link" id="<%= dom_id folder %>">
        <%= content_tag :div, nil, class: "card-status-top bg-#{folder.color}" %>

        <div class="card-body text-center">
          <div class="mb-3">
            <%= content_tag :span, class: "avatar avatar-sm bg-#{folder.color}" do %>
              <%= folder.name.first.capitalize %>
            <% end %>
          </div>

          <div class="card-title mb-1">
            <%= folder.name %>
          </div>

          <div class="text-muted">
            <%= pluralize(folder.notes.size, "Записи", locale: :ru) %>
          </div>
        </div>

        <%= link_to "Перейти", folder_path(folder), class: "card-btn" %>
      </div>

    </div>
  <% end %>
</div>

app/views/folders/new.html.erb
<h1 class="text-center text-muted">Создание папки</h1>

<div class="col-8 m-auto">
  <%= render "form", folder: @folder %>
</div>

app/views/folders/show.html.erb
<div class="d-flex justify-content-between">
  <div class="actions-header">
    <%= content_tag :div, class: "avatar text-white bg-#{@folder.color}" do %>
      <%= @folder.name.first.capitalize %>
    <% end %>

    <h1><%= @folder.name.capitalize %></h1>

    <ul class="list-inline mb-0 ms-4">
      <li class="list-inline-item">
        <%= link_to edit_folder_path, { title: "Изменить папку", class: "text-dark" } do %>
          <i class="bi bi-pen icon-sm"></i>
        <% end %>
      </li>

      <li class="list-inline-item ms-3">
        <%= button_to folder_path(@folder), { title: "Удалить папку", class: "btn-link text-dark" }, method: :delete do %>
          <i class="bi bi-x-lg icon-sm"></i>
        <% end %>
      </li>
    </ul>
  </div>

  <div class="col-4">
    <%= render partial: "notes/search_form" %>
  </div>
</div>


<% if @folder.notes.present? %>
  <div class="row row-cards mt-4" id="notes">
    <% @folder.notes.each do |note| %>
      <div class="col-6">
        <div class="card card-link" id="<%= dom_id note %>">
          <%= content_tag :div, nil, class: "card-status-start bg-#{@folder.color}" %>

          <div class="card-header">
            <h3 class="card-title">
              <%= link_to note.title, note_path(note), class: "text-decoration-none" %>
            </h3>
          </div>

          <div class="card-body">
            <%= note.content.to_plain_text.truncate(70) %>
          </div>

          <div class="card-footer border-0 bg-white">
            <% note.tag_list.each do |tag| %>
              <%= link_to notes_path(tagged: tag) do %>
                <%= content_tag :span, class: "badge rounded-pill bg-#{@folder.color}" do %>
                  <%= tag %>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="container-tight py-4">
    <div class="empty">
      <div class="empty-header">
        <i class="bi bi-card-heading"></i>
      </div>

      <p class="empty-subtitle text-muted">
        Здесь еще нет записей
      </p>

      <div class="empty-action">
        <%= link_to "Создать новую запись", new_note_path, class: "btn btn-#{@folder.color}" %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_alerts.html.erb
<% flash.each do |type, msg| %>
  <%= content_tag :div, class: "alert alert-#{type} alert-dismissible fade show", role: :alert do %>
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer footer-transparent d-print-none">
  <div class="container-xl">
    <div class="row text-center align-items-center flex-row-reverse">
      <div class="col-lg-auto ms-lg-auto">
        <ul class="list-inline list-inline-dots mb-0">
          <li class="list-inline-item">
            <%= link_to "Документация", "https://github.com/oksromn/knowledge-base", class: "link-secondary" %>
          </li>
          <li class="list-inline-item">
            <%= link_to "Выйти из аккаунта", destroy_user_session_path, data: { "turbo-method": :delete }, class: "link-secondary" %>
          </li>
        </ul>
      </div>

      <div class="col-12 col-lg-auto mt-3 mt-lg-0">
        <ul class="list-inline list-inline-dots mb-0">
          <li class="list-inline-item">Knowledge base © 2022</li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<aside class="navbar navbar-vertical navbar-expand-lg navbar-transparent">
  <div class="container-fluid">
    <h1 class="navbar-brand navbar-brand-autodark">
      <%= link_to root_path do %>
        <%= image_tag "logo.svg", size: 150, class: "navbar-brand-image" %>
      <% end %>
    </h1>

    <div class="navbar-collapse">
      <ul class="navbar-nav pt-lg-3">
        <li class="nav-item">
          <%= link_to notes_path, class: "nav-link" do %>
            <span class="nav-link-icon">
              <i class="bi bi-card-text icon"></i>
            </span>
            <span class="nav-link-title">
              Мои записи
            </span>
          <% end %>
        </li>

        <li class="nav-item">
          <%= link_to new_note_path, class: "nav-link" do %>
            <span class="nav-link-icon">
              <i class="bi bi-plus-square icon"></i>
            </span>
            <span class="nav-link-title">
              Добавить запись
            </span>
          <% end %>
        </li>

        <li class="nav-item">
          <%= link_to folders_path, class: "nav-link" do %>
            <span class="nav-link-icon">
              <i class="bi bi-archive icon"></i>
            </span>
            <span class="nav-link-title">
              Папки
            </span>
          <% end %>
        </li>

        <li class="nav-item">
          <%= link_to new_folder_path, class: "nav-link" do %>
            <span class="nav-link-icon">
              <i class="bi bi-journal-plus icon"></i>
            </span>
            <span class="nav-link-title">
              Создать папку
            </span>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</aside>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Knowledge base</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag "/favicon.ico" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="border-top-wide border-primary d-flex flex-column theme-light">
    <%= render partial: "layouts/alerts" %>

    <div class="page">
      <% if user_signed_in? %>
        <%= render partial: 'layouts/navbar' %>
        <div class="page-wrapper">
          <div class="page-body">
            <div class="container-xl">
              <div class="row">
                <div class="col-12">
                  <%= yield %>
                </div>
              </div>
            </div>
          </div>
          <%= render partial: "layouts/footer" %>
        </div>
      <% else %>
        <%= yield %>
      <% end %>
    </div>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with model: note, html: { class: "card mt-4" } do |form| %>
  <div class="card-status-top bg-dark"></div>
  <div class="card-body">
    <% if note.errors.any? %>
      <div style="color: red">
        <ul>
          <% note.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :title, "Название записи", class: "form-label" %>
      <%= form.text_field :title, placeholder: "Введите название", class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :content, "Содержание", class: "form-label" %>
      <%= form.rich_text_area :content, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :tag_list, "Теги", class: "form-label" %>
      <%= form.text_field :tag_list, value: note.tag_list.join(", "), class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :folder_id, "Папка", class: "form-label" %>
      <%= form.select :folder_id, options_from_collection_for_select(current_user.folders, :id, :name), {}, { class: "form-select" } %>
    </div>
  </div>

  <div class="card-footer text-end">
    <div class="d-flex justify-content-between">
      <%= link_to "Назад", root_path, class: "btn btn-link" %>
      <%= form.submit "Добавить", class: "btn btn-primary ms-auto" %>
    </div>
  </div>
<% end %>

app/views/notes/_note.html.erb
<div class="card" id="<%= dom_id note %>">
  <%= content_tag :div, nil, class: "card-status-top bg-#{note.folder.color}" %>

  <div class="card-header">
    <h3 class="card-title">
      <%= link_to note.title, note_path(note), class: "text-decoration-none" %>
    </h3>
  </div>

  <div class="card-body">
    <%= note.content %>
  </div>

  <div class="card-footer">
    <% note.tag_list.each do |tag| %>
      <%= link_to notes_path(tagged: tag) do %>
        <%= content_tag :span, class: "badge rounded-pill bg-#{note.folder.color}" do %>
          <%= tag %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/notes/_search_form.html.erb
<%= form_with url: notes_path, method: :get do |form| %>
  <div class="input-icon">
    <span class="input-icon-addon">
      <i class="bi bi-search"></i>
    </span>
    <%= form.text_field :tagged, placeholder: "Поиск по тегам", class: "form-control" %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Редактирование записи</h1>

<div class="col-8 m-auto">
  <%= render "form", note: @note %>
</div>

app/views/notes/index.html.erb
<div class="d-flex justify-content-between">
  <h1>Мои записи</h1>
  <div class="col-4">
    <%= render partial: "search_form" %>
  </div>
</div>

<% if @notes.present? %>
  <div class="row row-cards mt-4" id="notes">
    <% @notes.each do |note| %>
      <div class="col-6">
        <div class="card card-link" id="<%= dom_id note %>">
          <%= content_tag :div, nil, class: "card-status-start bg-#{note.folder.color}" %>

          <%= content_tag :div, class: "ribbon ribbon-top bg-#{note.folder.color}" do %>
            <%= link_to folder_path(note.folder), { title: note.folder.name, class: "text-decoration-none" } do %>
              <%= content_tag :span, class: "avatar avatar-sm bg-#{note.folder.color}" do %>
                <%= note.folder.name.first.capitalize %>
              <% end %>
            <% end %>
          <% end %>

          <div class="card-header justify-content-between">
            <h3 class="card-title">
              <%= link_to note.title, note_path(note), class: "text-decoration-none" %>
            </h3>
            <small class="text-muted me-4">
              <%= time_ago_in_words(note.created_at) %>
            </small>
          </div>

          <div class="card-body">
            <%= note.content.to_plain_text.truncate(70) %>
          </div>

          <div class="card-footer border-0 bg-white">
            <% note.tag_list.each do |tag| %>
              <%= link_to notes_path(tagged: tag) do %>
                <%= content_tag :span, class: "badge rounded-pill bg-#{note.folder.color}" do %>
                  <%= tag %>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="container-tight py-4">
    <div class="empty">
      <div class="empty-header">
        <i class="bi bi-card-heading"></i>
      </div>

      <p class="empty-subtitle text-muted">Здесь еще нет записей</p>

      <div class="empty-action">
        <%= link_to "Создать новую запись", new_note_path, class: "btn btn-dark" %>
      </div>
    </div>
  </div>
<% end %>

app/views/notes/new.html.erb
<h1 class="text-center text-muted">Новая запись</h1>

<div class="col-8 m-auto">
  <%= render "form", note: @note %>
</div>

app/views/notes/show.html.erb
<div class="d-flex justify-content-between">
  <div class="actions-header">
    <h1>Запись</h1>

    <ul class="list-inline mb-0 ms-4">
      <li class="list-inline-item">
        <%= link_to edit_note_path(@note), { title: "Изменить запись", class: "text-dark" } do %>
          <i class="bi bi-pen icon-sm"></i>
        <% end %>
      </li>

      <li class="list-inline-item ms-3">
        <%= button_to note_path(@note), { title: "Удалить запись", class: "btn-link text-dark" }, method: :delete do %>
          <i class="bi bi-x-lg icon-sm"></i>
        <% end %>
      </li>
    </ul>
  </div>
</div>

<div class="col-8 m-auto mt-4">
  <%= render @note %>
</div>